# -*- coding: utf-8 -*-
"""WebScrapeProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4cyZ40oSmmm1mHoZcjUIEenNbnfZVVG

**Scraping Data from a Real Website + Pandas**
"""

from bs4 import BeautifulSoup
import requests

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

page = requests.get(url)

soup = BeautifulSoup( page.text , 'html' )

#<table class="wikitable sortable jquery-tablesorter">
#</table>

Largest_Public_Company = soup.find_all('table' ,class_ ='wikitable')[0]

print(Largest_Public_Company)

Table_titles = Largest_Public_Company.find_all('th')

Table_titles

Company_table_titles = [ title.text.strip() for title in Table_titles ]
print(Company_table_titles)

import pandas as pd

df = pd.DataFrame(columns = Company_table_titles)
df

Row = Largest_Public_Company.find_all('tr')
Row

count=0
Row_Content=[]
for i in Row[1:]:
  count=count+1
  Row_Con = i.find_all('td')
  Row_Content = [title.text.strip() for title in Row_Con]
  #print(Row_Content)
  Length=len(df)
  df.loc[Length]=Row_Content
#count

df

df.to_csv('LargestCompanyDetails.csv',index= False)

